#!/bin/sh

topdir=$(dirname $0)/..

testprog=${topdir}/test/handle_stdio
if [ "$1" == "--valgrind" ]; then
	testprog="valgrind --leak-check=full --show-reachable=yes --track-origins=yes -q ${testprog}"
fi

suites=$(ls -1 ${topdir}/test/suites/)

for suite in ${suites}; do
	testcases=$(ls -1 ${topdir}/test/suites/${suite}/)
	for testcase in ${testcases}; do
		testpath=${topdir}/test/suites/${suite}/${testcase}
		cat ${testpath}/input | ${testprog} > ${testpath}/stdout 2> ${testpath}/stderr

		if cmp -s ${testpath}/output ${testpath}/stdout; then
			result="passed"
		else
			result="FAILED"
		fi

		if [ -s ${testpath}/stderr ]; then
			result="${result} (valgrind error)"
		fi

		echo ${suite}/${testcase} ${result}
	done
done
